spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8085  # Servicio de autenticación
          predicates:
            - Path=/auth/**
        - id: equipo-service # equipo
          uri: http://localhost:8080  # Microservicio 1
          predicates:
            - Path=/equipo/**
          filters:
            - StripPrefix=1


jwt:
  secret: my_secret_key  # Clave secreta usada para firmar los tokens


